pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker_hub')
    }

    stages {
        stage('Build') {
            steps {
                script {
		    // Build the Docker image
                    sh 'docker build -t alphatango1214/test ./helloWorld/'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push the Docker image to Docker Hub
                    docker.withRegistry('', 'docker_hub') {
                        docker.image('alphatango1214/test').push('latest')
                    }
                }
            }
        }
    }
}
