pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('Docker')
    }

    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Test begin'
                    // Build the Docker image
                    sh 'docker build -t alphatango1214/test ./helloWorld/'
                    echo 'This is where the change happened'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push the Docker image to Docker Hub
                    docker.withRegistry('', 'Docker') {
                        docker.image('alphatango1214/test').push('latest')
                    }
                }
            }
        }
        	stage('Connect_ssh') {
	    steps {
	        script {
	            sshagent(credentials: ['ssh_connect']) {
	                sh 'ssh -o StrictHostKeyChecking=no root@165.232.129.213 "docker pull alphatango1214/test:latest && docker run -d -p 8777:80 alphatango1214/test:latest"'
	            }
	        }
	    }
        
    }
}
